version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: sistemaropaclean
      MYSQL_USER: usuario1
      MYSQL_PASSWORD: passusuario1
    ports:
      - "3306:3306"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: usuario1
      PMA_PASSWORD: passusuario1
    ports:
      - "8080:80"